### ISSUE TITLE
Encoding incorrecto en algunas páginas del manual

### ISSUE THREAD

**Issue by xnt** [omegaup/karel.js#111]
Presiento que es por un BOM de la versión antigua de los manuales que se incorporó al repo, pero el encoding para caracteres no-ASCII parece ser incorrecto.

**Repro:**
1. Ir a https://omegaup.com/karel.js/manual/Karel.html

**Esperado:** Manual se despliega correcta y legiblemente
**Actual:** Errores de encoding en caracteres no-ASCII

**Pilón:** `document.charset` en consola reporta `"windows-1252"`

Solución sugerida: no sé si settear el meta de charset baste, o si toque hacer HTML encoding de los caracteres especiales.

Por favor, háganme saber si alguien ya está trabajando en esto. De lo contrario, me gustaría contribuir.

**Comment by lhchavez** [comment]
creo que va más allá del BOM y en realidad es que todo el documento está UTF-8 encoded[1]. estoy 99% seguro que tu sugerencia de settear el meta de charset es la solución correcta.

nadie está trabajando en esto, así que adelante :)

1: 
```shell
karel.js/manual$ file Karel.html 
Karel.html: HTML document, UTF-8 Unicode text
```
