### ISSUE TITLE
Karel se ejecuta y no se puede pausar cuando se cambia el delay mientras se está debugeando

### ISSUE THREAD

**Issue by pacharrin** [omegaup/karel.js#120]
pasos para reproducir:

poner el siguiente código 

```
iniciar-programa
    inicia-ejecucion
        repetir 1000 veces gira-izquierda;
        apagate;
    termina-ejecucion
finalizar-programa
```

poner el delay en 50

dar click en ejecutar
esperar 1 segundo y dar click en pausar
dar click en siguiente instrucción
cambiar delay a 0

comportamiento esperado el programa debería seguir pausado

comportamiento obtenido: el programa se sigue ejecutando y no se puede pausar

**Comment by categulario** [comment]
esto no pasa en el otro...

**Comment by kishtarn555** [comment]
Esto sigue pasando, Karel se cicla y no puedes detener, editar, o COPIAR el programa, lo que puedes hacer es recargar la pagina y confiar en que el auto-save de Karel te salve, pero tu mundo desaparece después de la siguiente ejecución.
