### ISSUE TITLE
[BUG] La pila de Karel se ve duplicada

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/karel.js#144]
No estoy seguro si es aquí o en el git de omegaup/omegaup, pero lo pondre te tambien aquí.

La pila de Karel pone la misma función varias veces.  Es un bug visual

Issue en omegaup (Algunos detalles extra y fotos):  omegaup/karel.js#148 

# Replicar

- Haz un codigo recursivo
- Reinicia el mundo
- Ejecuta el codigo
- Observa la pila

**Comment by Tweniee** [comment]
I would like to contribute to this, 
but not able to replicate the issue #148

can you please explain the steps in detail

**Comment by Tweniee** [comment]
@kishtarn555 Need help in reproducing the issue

**Comment by kishtarn555** [comment]
@Tweniee I don't know the steps to reproduce, it happens from time to time. 
I was using chrome 
windows 10

**Comment by kishtarn555** [comment]
@Tweniee Many months later, hahaha, but I think I now know what causes the issue. It is when you create a new world
