### ISSUE TITLE
nombrar una funcion en pascal que tiene como prefijo un token válido seguido de un guión medio es inválido

### ISSUE THREAD

**Issue by pacharrin** [omegaup/karel.js#52]
en karel de escritorio se permiten

**Comment by pacharrin** [comment]
código que falla

     define-nueva-instruccion avanza-pared como inicio
            mientras frente-libre hacer inicio
                avanza;
            fin;
        fin;

**Comment by pacharrin** [comment]
regresion!

me compil[o un programa con un afuncion llamada "avaza" no me marco error, solo ignoro esa linea'

**Comment by lhchavez** [comment]
el error no está relacionado con el problema original y posiblemente tenga que ver con #51.
