### ISSUE TITLE
Errores de compatibilidad con Karel 2011

### ISSUE THREAD

**Issue by kukogit** [omegaup/karel.js#55]
Karel.js no compila en JAVA cuando en los define utilizas guión medio como separador. Por ejmplo:

define orienta-este()
{
    ....
}

**Comment by lhchavez** [comment]
eso muy definitivamente no es Java :P yo voto por no permitir guiones medios e instituir el comportamiento de karel.js como el canónico.

**Comment by kukogit** [comment]
Otro de las cosas no compatibles que recuerdo son.

* Comentarios, no son iguales.
* El Karel OMI requiere quitar puntos y comas como estos (Karel.js no):
                turnright();
                if( nextToABeeper )
                    compute_second(succ(x));     <--- este punto y coma
                else
                    compute_second(x);

*

**Comment by lhchavez** [comment]
Creo que lo mejor es dejar de usar Karel 2011 y usar karel.js a partir de ahora. le arreglé un par de bugs a la gramática y esos jamás se van a arreglar en la versión de escritorio.

**Comment by frcepeda** [comment]
+1 a que los identifiers de java!karel sean consistentes con java
+1 a que karel.js sea canónico después de confirmar que no haga cosas raritas
(tal vez corriendo karel.js en vez de K_OS en el grader de omegaup podemos hacer un diff y ver si no rompe nada? o al menos en una muestra significativa...)

**Comment by lhchavez** [comment]
Se decidió que intencionalmente no se va a soportar compatibilidad con ninguna otra implementación de Karel para "motivar" a la gente a dejar de usar otras implementaciones no-oficiales. Sí, karel.js es la _única_ implementación de Karel oficial en la Olimpiada Mexicana de Informática.
