### ISSUE TITLE
Zumbadores Infinitos en el mundo no se muestran al abrir mundo.in

### ISSUE THREAD

**Issue by troyodk** [omegaup/karel.js#95]
Zumbadores Infinitos en el mundo no se muestran al abrir mundo.in

**Comment by Juanito98** [comment]
@troyodk ¿puedes proporcionarme un caso específico? Yo generé un .in y al abrirlo lo hace perfecto

**Comment by troyodk** [comment]
Parece que se arreglo con alguna de las nuevas versiones , antes ( desde el link que proporcionaba omegaup de karel.js) al guardar un mundo.in y después intentar abrirlo , desaparecian los zumbadores infinitos
